"""003_knowledge_and_dialog_profile

Revision ID: 2dcf72a0aadc
Revises: 8c578b45942c
Create Date: 2026-03-19 09:45:46.558349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2dcf72a0aadc'
down_revision: Union[str, Sequence[str], None] = '8c578b45942c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialog_profiles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('command_threshold', sa.Float(), nullable=False),
    sa.Column('route_strategy', sa.String(length=32), nullable=False),
    sa.Column('llm_provider', sa.String(length=64), nullable=True),
    sa.Column('llm_model', sa.String(length=64), nullable=True),
    sa.Column('session_timeout_min', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dialog_profiles_created_at', 'dialog_profiles', ['created_at'], unique=False)
    op.create_index('idx_dialog_profiles_status', 'dialog_profiles', ['status'], unique=False)
    op.create_table('knowledge_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_categories_parent', 'knowledge_categories', ['parent_id'], unique=False)
    op.create_index('idx_knowledge_categories_sort', 'knowledge_categories', ['sort_order'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['knowledge_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_docs_category', 'knowledge_documents', ['category_id'], unique=False)
    op.create_index('idx_knowledge_docs_created_at', 'knowledge_documents', ['created_at'], unique=False)
    op.create_index('idx_knowledge_docs_status', 'knowledge_documents', ['status'], unique=False)
    op.create_table('personas',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('personality', sa.String(length=500), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['dialog_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_persona_active_per_profile', 'personas', ['profile_id'], unique=True, postgresql_where='is_active = true')
    op.create_table('profile_library_bindings',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('library_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['intent_libraries.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['dialog_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'library_id', name='uq_profile_library')
    )
    op.create_table('profile_test_sessions',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['dialog_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('published_versions',
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('published_by', sa.UUID(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['dialog_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_published_version_active', 'published_versions', ['profile_id'], unique=True, postgresql_where="status = 'active'")
    op.create_table('document_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_chunks_document', 'document_chunks', ['document_id'], unique=False)
    op.create_index('idx_doc_chunks_index', 'document_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_table('profile_test_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('debug_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['profile_test_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_test_messages')
    op.drop_index('idx_doc_chunks_index', table_name='document_chunks')
    op.drop_index('idx_doc_chunks_document', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('uq_published_version_active', table_name='published_versions', postgresql_where="status = 'active'")
    op.drop_table('published_versions')
    op.drop_table('profile_test_sessions')
    op.drop_table('profile_library_bindings')
    op.drop_index('uq_persona_active_per_profile', table_name='personas', postgresql_where='is_active = true')
    op.drop_table('personas')
    op.drop_index('idx_knowledge_docs_status', table_name='knowledge_documents')
    op.drop_index('idx_knowledge_docs_created_at', table_name='knowledge_documents')
    op.drop_index('idx_knowledge_docs_category', table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index('idx_knowledge_categories_sort', table_name='knowledge_categories')
    op.drop_index('idx_knowledge_categories_parent', table_name='knowledge_categories')
    op.drop_table('knowledge_categories')
    op.drop_index('idx_dialog_profiles_status', table_name='dialog_profiles')
    op.drop_index('idx_dialog_profiles_created_at', table_name='dialog_profiles')
    op.drop_table('dialog_profiles')
    # ### end Alembic commands ###
