"""004_batch_test_and_monitoring

Revision ID: 432ff104576e
Revises: 2dcf72a0aadc
Create Date: 2026-03-19 09:54:16.830888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '432ff104576e'
down_revision: Union[str, Sequence[str], None] = '2dcf72a0aadc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_logs',
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=True),
    sa.Column('intent', sa.String(length=128), nullable=True),
    sa.Column('slots', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='success', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_request_logs_created_at', 'request_logs', ['created_at'], unique=False)
    op.create_index('ix_request_logs_device_id', 'request_logs', ['device_id'], unique=False)
    op.create_index('ix_request_logs_domain', 'request_logs', ['domain'], unique=False)
    op.create_index(op.f('ix_request_logs_request_id'), 'request_logs', ['request_id'], unique=False)
    op.create_index('ix_request_logs_session_id', 'request_logs', ['session_id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('operator', sa.String(length=8), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('window_minutes', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('notification_channels', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_events',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batch_tests',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_cases', sa.Integer(), nullable=False),
    sa.Column('completed_cases', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision_score', sa.Float(), nullable=True),
    sa.Column('recall_score', sa.Float(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['dialog_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_batch_tests_created_at', 'batch_tests', ['created_at'], unique=False)
    op.create_index('idx_batch_tests_status', 'batch_tests', ['status'], unique=False)
    op.create_table('test_cases',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('expected_intent', sa.String(length=128), nullable=True),
    sa.Column('expected_slots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_domain', sa.String(length=32), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_test_cases_batch_id', 'test_cases', ['batch_id'], unique=False)
    op.create_table('test_run_analyses',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confusion_top_n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('slot_error_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('low_score_samples', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_test_run_analyses_batch_id', 'test_run_analyses', ['batch_id'], unique=False)
    op.create_table('test_runs',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('actual_domain', sa.String(length=32), nullable=True),
    sa.Column('actual_intent', sa.String(length=128), nullable=True),
    sa.Column('actual_slots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_domain_hit', sa.Boolean(), nullable=True),
    sa.Column('is_intent_hit', sa.Boolean(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_test_runs_batch_id', 'test_runs', ['batch_id'], unique=False)
    op.create_index('idx_test_runs_case_id', 'test_runs', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_test_runs_case_id', table_name='test_runs')
    op.drop_index('idx_test_runs_batch_id', table_name='test_runs')
    op.drop_table('test_runs')
    op.drop_index('idx_test_run_analyses_batch_id', table_name='test_run_analyses')
    op.drop_table('test_run_analyses')
    op.drop_index('idx_test_cases_batch_id', table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index('idx_batch_tests_status', table_name='batch_tests')
    op.drop_index('idx_batch_tests_created_at', table_name='batch_tests')
    op.drop_table('batch_tests')
    op.drop_table('alert_events')
    op.drop_table('alert_rules')
    op.drop_index('ix_request_logs_session_id', table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_request_id'), table_name='request_logs')
    op.drop_index('ix_request_logs_domain', table_name='request_logs')
    op.drop_index('ix_request_logs_device_id', table_name='request_logs')
    op.drop_index('ix_request_logs_created_at', table_name='request_logs')
    op.drop_table('request_logs')
    # ### end Alembic commands ###
