"""002_intent_library_module

Revision ID: 8c578b45942c
Revises: c405763d5c15
Create Date: 2026-03-19 09:22:22.555982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c578b45942c'
down_revision: Union[str, Sequence[str], None] = 'c405763d5c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intent_libraries',
    sa.Column('library_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('default_confidence_threshold', sa.Float(), nullable=False),
    sa.Column('default_intent_f1_threshold', sa.Float(), nullable=False),
    sa.Column('default_slot_f1_threshold', sa.Float(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_key')
    )
    op.create_index('idx_intent_libraries_created_at', 'intent_libraries', ['created_at'], unique=False)
    op.create_index('idx_intent_libraries_language', 'intent_libraries', ['language'], unique=False)
    op.create_table('evaluation_datasets',
    sa.Column('library_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('samples', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('file_uri', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['library_id'], ['intent_libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ed_library_id', 'evaluation_datasets', ['library_id'], unique=False)
    op.create_table('training_datasets',
    sa.Column('library_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('intent_count', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('file_uri', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['library_id'], ['intent_libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_td_library_id', 'training_datasets', ['library_id'], unique=False)
    op.create_table('intents',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('intent_key', sa.String(length=128), nullable=False),
    sa.Column('name_zh', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('slot_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('follow_up_enabled', sa.Boolean(), nullable=False),
    sa.Column('follow_up_prompt', sa.String(length=500), nullable=True),
    sa.Column('hit_responses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('miss_response', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['training_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'intent_key', name='uq_intents_dataset_key')
    )
    op.create_index('idx_intents_dataset_id', 'intents', ['dataset_id'], unique=False)
    op.create_table('library_model_versions',
    sa.Column('library_id', sa.UUID(), nullable=False),
    sa.Column('version_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('train_dataset_id', sa.UUID(), nullable=True),
    sa.Column('train_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifact_type', sa.String(length=32), nullable=True),
    sa.Column('artifact_uri', sa.Text(), nullable=True),
    sa.Column('artifact_sha256', sa.String(length=64), nullable=True),
    sa.Column('package_uri', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_testable', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['library_id'], ['intent_libraries.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['train_dataset_id'], ['training_datasets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lmv_library_id', 'library_model_versions', ['library_id'], unique=False)
    op.create_index('idx_lmv_status', 'library_model_versions', ['status'], unique=False)
    op.create_index('uq_lmv_published', 'library_model_versions', ['library_id'], unique=True, postgresql_where='is_published = true')
    op.create_index('uq_lmv_testable', 'library_model_versions', ['library_id'], unique=True, postgresql_where='is_testable = true')
    op.create_table('slots',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('slot_key', sa.String(length=64), nullable=False),
    sa.Column('name_zh', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('slot_type', sa.String(length=16), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('prompt_text', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['training_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'slot_key', name='uq_slots_dataset_key')
    )
    op.create_index('idx_slots_dataset_id', 'slots', ['dataset_id'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('library_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('threshold_intent_f1', sa.Float(), nullable=False),
    sa.Column('threshold_slot_f1', sa.Float(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_samples', sa.Integer(), nullable=False),
    sa.Column('completed_samples', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['evaluation_datasets.id'], ),
    sa.ForeignKeyConstraint(['library_id'], ['intent_libraries.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['library_model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_er_created_at', 'evaluation_runs', ['created_at'], unique=False)
    op.create_index('idx_er_library_id', 'evaluation_runs', ['library_id'], unique=False)
    op.create_index('idx_er_model_version_id', 'evaluation_runs', ['model_version_id'], unique=False)
    op.create_index('idx_er_status', 'evaluation_runs', ['status'], unique=False)
    op.create_table('intent_test_sessions',
    sa.Column('library_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['intent_libraries.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['library_model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_its_library_id', 'intent_test_sessions', ['library_id'], unique=False)
    op.create_index('idx_its_model_id', 'intent_test_sessions', ['model_id'], unique=False)
    op.create_table('negative_examples',
    sa.Column('intent_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ne_intent_id', 'negative_examples', ['intent_id'], unique=False)
    op.create_table('similar_questions',
    sa.Column('intent_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=512), nullable=False),
    sa.Column('slot_annotations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sq_intent_id', 'similar_questions', ['intent_id'], unique=False)
    op.create_table('slot_entities',
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('synonyms', sa.String(length=1024), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_se_slot_id', 'slot_entities', ['slot_id'], unique=False)
    op.create_table('intent_test_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['intent_test_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_itm_session_id', 'intent_test_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_itm_session_id', table_name='intent_test_messages')
    op.drop_table('intent_test_messages')
    op.drop_index('idx_se_slot_id', table_name='slot_entities')
    op.drop_table('slot_entities')
    op.drop_index('idx_sq_intent_id', table_name='similar_questions')
    op.drop_table('similar_questions')
    op.drop_index('idx_ne_intent_id', table_name='negative_examples')
    op.drop_table('negative_examples')
    op.drop_index('idx_its_model_id', table_name='intent_test_sessions')
    op.drop_index('idx_its_library_id', table_name='intent_test_sessions')
    op.drop_table('intent_test_sessions')
    op.drop_index('idx_er_status', table_name='evaluation_runs')
    op.drop_index('idx_er_model_version_id', table_name='evaluation_runs')
    op.drop_index('idx_er_library_id', table_name='evaluation_runs')
    op.drop_index('idx_er_created_at', table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index('idx_slots_dataset_id', table_name='slots')
    op.drop_table('slots')
    op.drop_index('uq_lmv_testable', table_name='library_model_versions', postgresql_where='is_testable = true')
    op.drop_index('uq_lmv_published', table_name='library_model_versions', postgresql_where='is_published = true')
    op.drop_index('idx_lmv_status', table_name='library_model_versions')
    op.drop_index('idx_lmv_library_id', table_name='library_model_versions')
    op.drop_table('library_model_versions')
    op.drop_index('idx_intents_dataset_id', table_name='intents')
    op.drop_table('intents')
    op.drop_index('idx_td_library_id', table_name='training_datasets')
    op.drop_table('training_datasets')
    op.drop_index('idx_ed_library_id', table_name='evaluation_datasets')
    op.drop_table('evaluation_datasets')
    op.drop_index('idx_intent_libraries_language', table_name='intent_libraries')
    op.drop_index('idx_intent_libraries_created_at', table_name='intent_libraries')
    op.drop_table('intent_libraries')
    # ### end Alembic commands ###
