"""initial_schema

Revision ID: 898ef904efc1
Revises: 
Create Date: 2026-04-01 09:41:10.329702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898ef904efc1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.String(length=32), nullable=False),
    sa.Column('target_user_id', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capability_definition',
    sa.Column('capability_key', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('condition_note', sa.String(length=100), nullable=True),
    sa.Column('module_key', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('capability_key')
    )
    op.create_table('command_library',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('library_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('model_limit', sa.Integer(), nullable=False),
    sa.Column('default_thresholds_json', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_library_language'), 'command_library', ['language'], unique=False)
    op.create_index(op.f('ix_command_library_library_key'), 'command_library', ['library_key'], unique=True)
    op.create_table('device_privacy_delete_request',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('requested_by', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confirmation_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_privacy_delete_request_confirmation_token'), 'device_privacy_delete_request', ['confirmation_token'], unique=True)
    op.create_index(op.f('ix_device_privacy_delete_request_created_at'), 'device_privacy_delete_request', ['created_at'], unique=False)
    op.create_index(op.f('ix_device_privacy_delete_request_device_id'), 'device_privacy_delete_request', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_privacy_delete_request_expires_at'), 'device_privacy_delete_request', ['expires_at'], unique=False)
    op.create_index(op.f('ix_device_privacy_delete_request_requested_by'), 'device_privacy_delete_request', ['requested_by'], unique=False)
    op.create_table('dialog_profile',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('llm_model', sa.String(length=50), nullable=False),
    sa.Column('routing_strategy', sa.String(length=30), nullable=False),
    sa.Column('persona_name', sa.String(length=50), nullable=False),
    sa.Column('persona_prompt', sa.Text(), nullable=False),
    sa.Column('intent_threshold', sa.Float(), nullable=False),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=32), nullable=True),
    sa.Column('publish_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialog_profile_name'), 'dialog_profile', ['name'], unique=True)
    op.create_index(op.f('ix_dialog_profile_status'), 'dialog_profile', ['status'], unique=False)
    op.create_table('knowledge_category',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('ready_document_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_category_name'), 'knowledge_category', ['name'], unique=True)
    op.create_index(op.f('ix_knowledge_category_status'), 'knowledge_category', ['status'], unique=False)
    op.create_table('monitoring_alert_rule',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('metric_key', sa.String(length=40), nullable=False),
    sa.Column('comparator', sa.String(length=10), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('window_minutes', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_alert_rule_enabled'), 'monitoring_alert_rule', ['enabled'], unique=False)
    op.create_index(op.f('ix_monitoring_alert_rule_metric_key'), 'monitoring_alert_rule', ['metric_key'], unique=False)
    op.create_index(op.f('ix_monitoring_alert_rule_name'), 'monitoring_alert_rule', ['name'], unique=True)
    op.create_table('monitoring_metric_snapshot',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('window_key', sa.String(length=20), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('qps', sa.Float(), nullable=False),
    sa.Column('avg_latency_ms', sa.Integer(), nullable=False),
    sa.Column('p95_latency_ms', sa.Integer(), nullable=False),
    sa.Column('p99_latency_ms', sa.Integer(), nullable=False),
    sa.Column('accuracy_rate', sa.Float(), nullable=True),
    sa.Column('error_rate', sa.Float(), nullable=False),
    sa.Column('route_distribution_json', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_metric_snapshot_captured_at'), 'monitoring_metric_snapshot', ['captured_at'], unique=False)
    op.create_index(op.f('ix_monitoring_metric_snapshot_window_key'), 'monitoring_metric_snapshot', ['window_key'], unique=False)
    op.create_table('published_version',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_published_version_entity_id'), 'published_version', ['entity_id'], unique=False)
    op.create_index(op.f('ix_published_version_entity_type'), 'published_version', ['entity_type'], unique=False)
    op.create_table('request_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=True),
    sa.Column('route_type', sa.String(length=30), nullable=False),
    sa.Column('intent_name', sa.String(length=80), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('is_error', sa.Boolean(), nullable=False),
    sa.Column('accuracy_hit', sa.Boolean(), nullable=True),
    sa.Column('request_json', sa.Text(), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_log_created_at'), 'request_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_log_device_id'), 'request_log', ['device_id'], unique=False)
    op.create_index(op.f('ix_request_log_intent_name'), 'request_log', ['intent_name'], unique=False)
    op.create_index(op.f('ix_request_log_is_error'), 'request_log', ['is_error'], unique=False)
    op.create_index(op.f('ix_request_log_latency_ms'), 'request_log', ['latency_ms'], unique=False)
    op.create_index(op.f('ix_request_log_request_id'), 'request_log', ['request_id'], unique=True)
    op.create_index(op.f('ix_request_log_route_type'), 'request_log', ['route_type'], unique=False)
    op.create_index(op.f('ix_request_log_session_id'), 'request_log', ['session_id'], unique=False)
    op.create_table('role_definition',
    sa.Column('role_key', sa.String(length=20), nullable=False),
    sa.Column('role_label', sa.String(length=50), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('role_key')
    )
    op.create_table('batch_test_run',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('profile_name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('case_count', sa.Integer(), nullable=False),
    sa.Column('executed_count', sa.Integer(), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('response_p95_ms', sa.Integer(), nullable=True),
    sa.Column('threshold_snapshot_json', sa.Text(), nullable=False),
    sa.Column('analysis_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['dialog_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_test_run_name'), 'batch_test_run', ['name'], unique=False)
    op.create_index(op.f('ix_batch_test_run_profile_id'), 'batch_test_run', ['profile_id'], unique=False)
    op.create_index(op.f('ix_batch_test_run_status'), 'batch_test_run', ['status'], unique=False)
    op.create_table('device_session',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('device_context_json', sa.Text(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['dialog_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_session_created_at'), 'device_session', ['created_at'], unique=False)
    op.create_index(op.f('ix_device_session_device_id'), 'device_session', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_session_expires_at'), 'device_session', ['expires_at'], unique=False)
    op.create_index(op.f('ix_device_session_profile_id'), 'device_session', ['profile_id'], unique=False)
    op.create_table('dialog_profile_library_binding',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('library_id', sa.String(length=32), nullable=False),
    sa.Column('library_name', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('published_model_name', sa.String(length=80), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['command_library.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['dialog_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialog_profile_library_binding_language'), 'dialog_profile_library_binding', ['language'], unique=False)
    op.create_index(op.f('ix_dialog_profile_library_binding_library_id'), 'dialog_profile_library_binding', ['library_id'], unique=False)
    op.create_index(op.f('ix_dialog_profile_library_binding_profile_id'), 'dialog_profile_library_binding', ['profile_id'], unique=False)
    op.create_table('knowledge_document',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('category_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('valid_content_json', sa.Text(), nullable=True),
    sa.Column('filtered_fields_json', sa.Text(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('index_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['knowledge_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_document_category_id'), 'knowledge_document', ['category_id'], unique=False)
    op.create_index(op.f('ix_knowledge_document_format'), 'knowledge_document', ['format'], unique=False)
    op.create_index(op.f('ix_knowledge_document_status'), 'knowledge_document', ['status'], unique=False)
    op.create_table('library_dataset',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('library_id', sa.String(length=32), nullable=False),
    sa.Column('dataset_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('bound_model_id', sa.String(length=32), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['command_library.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_dataset_dataset_type'), 'library_dataset', ['dataset_type'], unique=False)
    op.create_index(op.f('ix_library_dataset_library_id'), 'library_dataset', ['library_id'], unique=False)
    op.create_table('monitoring_alert_event',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['monitoring_alert_rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_alert_event_rule_id'), 'monitoring_alert_event', ['rule_id'], unique=False)
    op.create_index(op.f('ix_monitoring_alert_event_status'), 'monitoring_alert_event', ['status'], unique=False)
    op.create_index(op.f('ix_monitoring_alert_event_triggered_at'), 'monitoring_alert_event', ['triggered_at'], unique=False)
    op.create_table('role_capability_binding',
    sa.Column('role_key', sa.String(length=20), nullable=False),
    sa.Column('capability_key', sa.String(length=64), nullable=False),
    sa.Column('condition_note', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['capability_key'], ['capability_definition.capability_key'], ),
    sa.ForeignKeyConstraint(['role_key'], ['role_definition.role_key'], ),
    sa.PrimaryKeyConstraint('role_key', 'capability_key')
    )
    op.create_table('test_session',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('device_context_json', sa.Text(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['dialog_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_session_profile_id'), 'test_session', ['profile_id'], unique=False)
    op.create_table('user_account',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_key', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('is_builtin_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_key'], ['role_definition.role_key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_account_role_key'), 'user_account', ['role_key'], unique=False)
    op.create_index(op.f('ix_user_account_status'), 'user_account', ['status'], unique=False)
    op.create_index(op.f('ix_user_account_username'), 'user_account', ['username'], unique=True)
    op.create_table('auth_session',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_auth_session_user_id'), 'auth_session', ['user_id'], unique=False)
    op.create_table('batch_test_analysis',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('batch_id', sa.String(length=32), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=False),
    sa.Column('confusion_matrix_json', sa.Text(), nullable=False),
    sa.Column('root_causes_json', sa.Text(), nullable=False),
    sa.Column('recommendations_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_test_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_test_analysis_batch_id'), 'batch_test_analysis', ['batch_id'], unique=False)
    op.create_table('batch_test_case',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('batch_id', sa.String(length=32), nullable=False),
    sa.Column('case_no', sa.String(length=20), nullable=False),
    sa.Column('utterance', sa.String(length=300), nullable=False),
    sa.Column('expected_route', sa.String(length=30), nullable=False),
    sa.Column('expected_intent', sa.String(length=80), nullable=True),
    sa.Column('expected_slots_json', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('tuned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_test_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_test_case_batch_id'), 'batch_test_case', ['batch_id'], unique=False)
    op.create_table('knowledge_retrieval_probe',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('query', sa.String(length=300), nullable=False),
    sa.Column('hit', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('response_preview', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_retrieval_probe_document_id'), 'knowledge_retrieval_probe', ['document_id'], unique=False)
    op.create_table('library_model_version',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('library_id', sa.String(length=32), nullable=False),
    sa.Column('version_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('training_dataset_id', sa.String(length=32), nullable=True),
    sa.Column('artifact_uri', sa.Text(), nullable=True),
    sa.Column('artifact_format', sa.String(length=20), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('is_testable', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['command_library.id'], ),
    sa.ForeignKeyConstraint(['training_dataset_id'], ['library_dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_model_version_library_id'), 'library_model_version', ['library_id'], unique=False)
    op.create_index(op.f('ix_library_model_version_status'), 'library_model_version', ['status'], unique=False)
    op.create_table('test_session_message',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('debug_trace_json', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['test_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_session_message_role'), 'test_session_message', ['role'], unique=False)
    op.create_index(op.f('ix_test_session_message_session_id'), 'test_session_message', ['session_id'], unique=False)
    op.create_table('batch_test_result',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('batch_id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('actual_route', sa.String(length=30), nullable=False),
    sa.Column('actual_intent', sa.String(length=80), nullable=True),
    sa.Column('actual_slots_json', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_test_run.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['batch_test_case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_test_result_batch_id'), 'batch_test_result', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batch_test_result_case_id'), 'batch_test_result', ['case_id'], unique=False)
    op.create_table('evaluation_run',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=32), nullable=False),
    sa.Column('dataset_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('threshold_snapshot_json', sa.Text(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('slot_f1', sa.Float(), nullable=True),
    sa.Column('response_p95_ms', sa.Integer(), nullable=True),
    sa.Column('analysis_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['library_dataset.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['library_model_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_run_model_id'), 'evaluation_run', ['model_id'], unique=False)
    op.create_index(op.f('ix_evaluation_run_status'), 'evaluation_run', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluation_run_status'), table_name='evaluation_run')
    op.drop_index(op.f('ix_evaluation_run_model_id'), table_name='evaluation_run')
    op.drop_table('evaluation_run')
    op.drop_index(op.f('ix_batch_test_result_case_id'), table_name='batch_test_result')
    op.drop_index(op.f('ix_batch_test_result_batch_id'), table_name='batch_test_result')
    op.drop_table('batch_test_result')
    op.drop_index(op.f('ix_test_session_message_session_id'), table_name='test_session_message')
    op.drop_index(op.f('ix_test_session_message_role'), table_name='test_session_message')
    op.drop_table('test_session_message')
    op.drop_index(op.f('ix_library_model_version_status'), table_name='library_model_version')
    op.drop_index(op.f('ix_library_model_version_library_id'), table_name='library_model_version')
    op.drop_table('library_model_version')
    op.drop_index(op.f('ix_knowledge_retrieval_probe_document_id'), table_name='knowledge_retrieval_probe')
    op.drop_table('knowledge_retrieval_probe')
    op.drop_index(op.f('ix_batch_test_case_batch_id'), table_name='batch_test_case')
    op.drop_table('batch_test_case')
    op.drop_index(op.f('ix_batch_test_analysis_batch_id'), table_name='batch_test_analysis')
    op.drop_table('batch_test_analysis')
    op.drop_index(op.f('ix_auth_session_user_id'), table_name='auth_session')
    op.drop_table('auth_session')
    op.drop_index(op.f('ix_user_account_username'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_status'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_role_key'), table_name='user_account')
    op.drop_table('user_account')
    op.drop_index(op.f('ix_test_session_profile_id'), table_name='test_session')
    op.drop_table('test_session')
    op.drop_table('role_capability_binding')
    op.drop_index(op.f('ix_monitoring_alert_event_triggered_at'), table_name='monitoring_alert_event')
    op.drop_index(op.f('ix_monitoring_alert_event_status'), table_name='monitoring_alert_event')
    op.drop_index(op.f('ix_monitoring_alert_event_rule_id'), table_name='monitoring_alert_event')
    op.drop_table('monitoring_alert_event')
    op.drop_index(op.f('ix_library_dataset_library_id'), table_name='library_dataset')
    op.drop_index(op.f('ix_library_dataset_dataset_type'), table_name='library_dataset')
    op.drop_table('library_dataset')
    op.drop_index(op.f('ix_knowledge_document_status'), table_name='knowledge_document')
    op.drop_index(op.f('ix_knowledge_document_format'), table_name='knowledge_document')
    op.drop_index(op.f('ix_knowledge_document_category_id'), table_name='knowledge_document')
    op.drop_table('knowledge_document')
    op.drop_index(op.f('ix_dialog_profile_library_binding_profile_id'), table_name='dialog_profile_library_binding')
    op.drop_index(op.f('ix_dialog_profile_library_binding_library_id'), table_name='dialog_profile_library_binding')
    op.drop_index(op.f('ix_dialog_profile_library_binding_language'), table_name='dialog_profile_library_binding')
    op.drop_table('dialog_profile_library_binding')
    op.drop_index(op.f('ix_device_session_profile_id'), table_name='device_session')
    op.drop_index(op.f('ix_device_session_expires_at'), table_name='device_session')
    op.drop_index(op.f('ix_device_session_device_id'), table_name='device_session')
    op.drop_index(op.f('ix_device_session_created_at'), table_name='device_session')
    op.drop_table('device_session')
    op.drop_index(op.f('ix_batch_test_run_status'), table_name='batch_test_run')
    op.drop_index(op.f('ix_batch_test_run_profile_id'), table_name='batch_test_run')
    op.drop_index(op.f('ix_batch_test_run_name'), table_name='batch_test_run')
    op.drop_table('batch_test_run')
    op.drop_table('role_definition')
    op.drop_index(op.f('ix_request_log_session_id'), table_name='request_log')
    op.drop_index(op.f('ix_request_log_route_type'), table_name='request_log')
    op.drop_index(op.f('ix_request_log_request_id'), table_name='request_log')
    op.drop_index(op.f('ix_request_log_latency_ms'), table_name='request_log')
    op.drop_index(op.f('ix_request_log_is_error'), table_name='request_log')
    op.drop_index(op.f('ix_request_log_intent_name'), table_name='request_log')
    op.drop_index(op.f('ix_request_log_device_id'), table_name='request_log')
    op.drop_index(op.f('ix_request_log_created_at'), table_name='request_log')
    op.drop_table('request_log')
    op.drop_index(op.f('ix_published_version_entity_type'), table_name='published_version')
    op.drop_index(op.f('ix_published_version_entity_id'), table_name='published_version')
    op.drop_table('published_version')
    op.drop_index(op.f('ix_monitoring_metric_snapshot_window_key'), table_name='monitoring_metric_snapshot')
    op.drop_index(op.f('ix_monitoring_metric_snapshot_captured_at'), table_name='monitoring_metric_snapshot')
    op.drop_table('monitoring_metric_snapshot')
    op.drop_index(op.f('ix_monitoring_alert_rule_name'), table_name='monitoring_alert_rule')
    op.drop_index(op.f('ix_monitoring_alert_rule_metric_key'), table_name='monitoring_alert_rule')
    op.drop_index(op.f('ix_monitoring_alert_rule_enabled'), table_name='monitoring_alert_rule')
    op.drop_table('monitoring_alert_rule')
    op.drop_index(op.f('ix_knowledge_category_status'), table_name='knowledge_category')
    op.drop_index(op.f('ix_knowledge_category_name'), table_name='knowledge_category')
    op.drop_table('knowledge_category')
    op.drop_index(op.f('ix_dialog_profile_status'), table_name='dialog_profile')
    op.drop_index(op.f('ix_dialog_profile_name'), table_name='dialog_profile')
    op.drop_table('dialog_profile')
    op.drop_index(op.f('ix_device_privacy_delete_request_requested_by'), table_name='device_privacy_delete_request')
    op.drop_index(op.f('ix_device_privacy_delete_request_expires_at'), table_name='device_privacy_delete_request')
    op.drop_index(op.f('ix_device_privacy_delete_request_device_id'), table_name='device_privacy_delete_request')
    op.drop_index(op.f('ix_device_privacy_delete_request_created_at'), table_name='device_privacy_delete_request')
    op.drop_index(op.f('ix_device_privacy_delete_request_confirmation_token'), table_name='device_privacy_delete_request')
    op.drop_table('device_privacy_delete_request')
    op.drop_index(op.f('ix_command_library_library_key'), table_name='command_library')
    op.drop_index(op.f('ix_command_library_language'), table_name='command_library')
    op.drop_table('command_library')
    op.drop_table('capability_definition')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
